### ISSUE TITLE
The apps makes notifications to be repeated

### ISSUE THREAD

**Issue by NickCis** [CODeRUS/android-notifications#1]
After installing the app, the jolla-messages app notifications started to be repeated, instead of grouped in one entry.

I attach an image of the problem.

![20150224155816](https://cloud.githubusercontent.com/assets/174561/6356736/2e215d90-bc3e-11e4-8c52-169995bacfd0.jpg)

**Comment by CODeRUS** [comment]
Hm, seems something wrong with commhistoryd

**Comment by CODeRUS** [comment]
Fixed in v0.2.0

**Comment by NickCis** [comment]
Thanks for the quick fix!
