### ISSUE TITLE
continuously updated notifications

### ISSUE THREAD

**Issue by wanderer1988** [CODeRUS/android-notifications#2]
Some Android apps have notifications which are updated continuously. One example for this is the Amazon appstore: If you install a new app, the progress of the download (in %) is shown in the notifications and updated continuously. Unfortunately the android-notifications app triggers a notification sound on every single update, so it is ringing permanently during a download.
There should be a special handling for such continuously updated notifications.

**Comment by CODeRUS** [comment]
no
